### ISSUE TITLE
OC HCA Extract errs out.

### ISSUE THREAD

**Issue by klenwell** [klenwell/covid-19#19]
It looks like OC HCA has restricted access to data. See directory:

- https://services2.arcgis.com/LORzk2hk9xzHouw9/ArcGIS/rest/services

`occovid_cases_csv` is no longer listed. However, [occovid_case_csv](https://services2.arcgis.com/LORzk2hk9xzHouw9/ArcGIS/rest/services/occovid_case_csv/FeatureServer/0) is and it lists **Last Edit Date** as `7/14/2020 9:06:45 PM`.

So maybe county just renamed it.

### Error
```
$ python app.py oc daily                                                          
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    app.run()
  File "/home/klenwell/pyenv/versions/covid-19/lib/python3.8/site-packages/cement/core/foundation.py", line 916, in run
    return_val = self.controller._dispatch()
  File "/home/klenwell/pyenv/versions/covid-19/lib/python3.8/site-packages/cement/ext/ext_argparse.py", line 808, in _di
spatch
    return func()
  File "/home/klenwell/projects/covid-19/covid_app/controllers/oc_controller.py", line 18, in daily
    csv = OCHealthService.export_daily_csv()
  File "/home/klenwell/projects/covid-19/covid_app/services/oc_health_service.py", line 33, in export_daily_csv
    result = service.output_daily_csv()
  File "/home/klenwell/projects/covid-19/covid_app/services/oc_health_service.py", line 107, in output_daily_csv
    for row in self.daily_csv_rows:
  File "/home/klenwell/pyenv/versions/covid-19/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/home/klenwell/projects/covid-19/covid_app/services/oc_health_service.py", line 79, in daily_csv_rows
    next_date = self.daily_csv_start_date
  File "/home/klenwell/pyenv/versions/covid-19/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/home/klenwell/projects/covid-19/covid_app/services/oc_health_service.py", line 90, in daily_csv_start_date
    return self.daily_extract.starts_on
  File "/home/klenwell/projects/covid-19/covid_app/extracts/oc_hca/versions/daily_covid19_extract_v3.py", line 101, in s
tarts_on
    return self.dates[0]
  File "/home/klenwell/projects/covid-19/covid_app/extracts/oc_hca/versions/daily_covid19_extract_v3.py", line 97, in da
tes
    return sorted(self.new_cases.keys())
  File "/home/klenwell/pyenv/versions/covid-19/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/home/klenwell/projects/covid-19/covid_app/extracts/oc_hca/versions/daily_covid19_extract_v3.py", line 68, in ne
w_cases
    daily_logs = self.daily_case_logs
  File "/home/klenwell/pyenv/versions/covid-19/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/home/klenwell/projects/covid-19/covid_app/extracts/oc_hca/versions/daily_covid19_extract_v3.py", line 42, in daily_case_logs
    return self.extract_from_json_data(json_data)
  File "/home/klenwell/projects/covid-19/covid_app/extracts/oc_hca/versions/daily_covid19_extract_v3.py", line 133, in extract_from_json_data
    features = json_data['features']
KeyError: 'features'
```

**Comment by klenwell** [comment]
## Resolved
OC HCA changed CSV data endpoints:

- `occovid_cases_csv` ➙ `occovid_case_csv`
- `occovid_testing_csv` ➙ `occovid_pcr_csv`
- `occovid_deaths_csv` ➙ `occovid_death_csv`

Simply updated vars in extract class.
